// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shared.proto

package boa.types;

public final class Shared {
  private Shared() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code boa.types.ChangeKind}
   */
  public enum ChangeKind
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ADDED = 1;</code>
     */
    ADDED(0, 1),
    /**
     * <code>DELETED = 2;</code>
     */
    DELETED(1, 2),
    /**
     * <code>MODIFIED = 3;</code>
     */
    MODIFIED(2, 3),
    ;

    /**
     * <code>ADDED = 1;</code>
     */
    public static final int ADDED_VALUE = 1;
    /**
     * <code>DELETED = 2;</code>
     */
    public static final int DELETED_VALUE = 2;
    /**
     * <code>MODIFIED = 3;</code>
     */
    public static final int MODIFIED_VALUE = 3;


    public final int getNumber() { return value; }

    public static ChangeKind valueOf(int value) {
      switch (value) {
        case 1: return ADDED;
        case 2: return DELETED;
        case 3: return MODIFIED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ChangeKind>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ChangeKind>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ChangeKind>() {
            public ChangeKind findValueByNumber(int number) {
              return ChangeKind.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return boa.types.Shared.getDescriptor().getEnumTypes().get(0);
    }

    private static final ChangeKind[] VALUES = values();

    public static ChangeKind valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ChangeKind(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:boa.types.ChangeKind)
  }

  public interface PersonOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string username = 1;
    /**
     * <code>required string username = 1;</code>
     */
    boolean hasUsername();
    /**
     * <code>required string username = 1;</code>
     */
    java.lang.String getUsername();
    /**
     * <code>required string username = 1;</code>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    // required string real_name = 2;
    /**
     * <code>required string real_name = 2;</code>
     */
    boolean hasRealName();
    /**
     * <code>required string real_name = 2;</code>
     */
    java.lang.String getRealName();
    /**
     * <code>required string real_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getRealNameBytes();

    // required string email = 3;
    /**
     * <code>required string email = 3;</code>
     */
    boolean hasEmail();
    /**
     * <code>required string email = 3;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>required string email = 3;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    // repeated .boa.types.Person followers = 4;
    /**
     * <code>repeated .boa.types.Person followers = 4;</code>
     */
    java.util.List<boa.types.Shared.Person> 
        getFollowersList();
    /**
     * <code>repeated .boa.types.Person followers = 4;</code>
     */
    boa.types.Shared.Person getFollowers(int index);
    /**
     * <code>repeated .boa.types.Person followers = 4;</code>
     */
    int getFollowersCount();
    /**
     * <code>repeated .boa.types.Person followers = 4;</code>
     */
    java.util.List<? extends boa.types.Shared.PersonOrBuilder> 
        getFollowersOrBuilderList();
    /**
     * <code>repeated .boa.types.Person followers = 4;</code>
     */
    boa.types.Shared.PersonOrBuilder getFollowersOrBuilder(
        int index);

    // repeated .boa.types.Person followings = 5;
    /**
     * <code>repeated .boa.types.Person followings = 5;</code>
     */
    java.util.List<boa.types.Shared.Person> 
        getFollowingsList();
    /**
     * <code>repeated .boa.types.Person followings = 5;</code>
     */
    boa.types.Shared.Person getFollowings(int index);
    /**
     * <code>repeated .boa.types.Person followings = 5;</code>
     */
    int getFollowingsCount();
    /**
     * <code>repeated .boa.types.Person followings = 5;</code>
     */
    java.util.List<? extends boa.types.Shared.PersonOrBuilder> 
        getFollowingsOrBuilderList();
    /**
     * <code>repeated .boa.types.Person followings = 5;</code>
     */
    boa.types.Shared.PersonOrBuilder getFollowingsOrBuilder(
        int index);

    // repeated string organizations = 6;
    /**
     * <code>repeated string organizations = 6;</code>
     */
    java.util.List<java.lang.String>
    getOrganizationsList();
    /**
     * <code>repeated string organizations = 6;</code>
     */
    int getOrganizationsCount();
    /**
     * <code>repeated string organizations = 6;</code>
     */
    java.lang.String getOrganizations(int index);
    /**
     * <code>repeated string organizations = 6;</code>
     */
    com.google.protobuf.ByteString
        getOrganizationsBytes(int index);
  }
  /**
   * Protobuf type {@code boa.types.Person}
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessage
      implements PersonOrBuilder {
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Person(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Person defaultInstance;
    public static Person getDefaultInstance() {
      return defaultInstance;
    }

    public Person getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              username_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              realName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              email_ = input.readBytes();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                followers_ = new java.util.ArrayList<boa.types.Shared.Person>();
                mutable_bitField0_ |= 0x00000008;
              }
              followers_.add(input.readMessage(boa.types.Shared.Person.PARSER, extensionRegistry));
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                followings_ = new java.util.ArrayList<boa.types.Shared.Person>();
                mutable_bitField0_ |= 0x00000010;
              }
              followings_.add(input.readMessage(boa.types.Shared.Person.PARSER, extensionRegistry));
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                organizations_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000020;
              }
              organizations_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          followers_ = java.util.Collections.unmodifiableList(followers_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          followings_ = java.util.Collections.unmodifiableList(followings_);
        }
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          organizations_ = new com.google.protobuf.UnmodifiableLazyStringList(organizations_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return boa.types.Shared.internal_static_boa_types_Person_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return boa.types.Shared.internal_static_boa_types_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              boa.types.Shared.Person.class, boa.types.Shared.Person.Builder.class);
    }

    public static com.google.protobuf.Parser<Person> PARSER =
        new com.google.protobuf.AbstractParser<Person>() {
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string username = 1;
    public static final int USERNAME_FIELD_NUMBER = 1;
    private java.lang.Object username_;
    /**
     * <code>required string username = 1;</code>
     */
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string username = 1;</code>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          username_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string username = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string real_name = 2;
    public static final int REAL_NAME_FIELD_NUMBER = 2;
    private java.lang.Object realName_;
    /**
     * <code>required string real_name = 2;</code>
     */
    public boolean hasRealName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string real_name = 2;</code>
     */
    public java.lang.String getRealName() {
      java.lang.Object ref = realName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          realName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string real_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRealNameBytes() {
      java.lang.Object ref = realName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        realName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string email = 3;
    public static final int EMAIL_FIELD_NUMBER = 3;
    private java.lang.Object email_;
    /**
     * <code>required string email = 3;</code>
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string email = 3;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string email = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .boa.types.Person followers = 4;
    public static final int FOLLOWERS_FIELD_NUMBER = 4;
    private java.util.List<boa.types.Shared.Person> followers_;
    /**
     * <code>repeated .boa.types.Person followers = 4;</code>
     */
    public java.util.List<boa.types.Shared.Person> getFollowersList() {
      return followers_;
    }
    /**
     * <code>repeated .boa.types.Person followers = 4;</code>
     */
    public java.util.List<? extends boa.types.Shared.PersonOrBuilder> 
        getFollowersOrBuilderList() {
      return followers_;
    }
    /**
     * <code>repeated .boa.types.Person followers = 4;</code>
     */
    public int getFollowersCount() {
      return followers_.size();
    }
    /**
     * <code>repeated .boa.types.Person followers = 4;</code>
     */
    public boa.types.Shared.Person getFollowers(int index) {
      return followers_.get(index);
    }
    /**
     * <code>repeated .boa.types.Person followers = 4;</code>
     */
    public boa.types.Shared.PersonOrBuilder getFollowersOrBuilder(
        int index) {
      return followers_.get(index);
    }

    // repeated .boa.types.Person followings = 5;
    public static final int FOLLOWINGS_FIELD_NUMBER = 5;
    private java.util.List<boa.types.Shared.Person> followings_;
    /**
     * <code>repeated .boa.types.Person followings = 5;</code>
     */
    public java.util.List<boa.types.Shared.Person> getFollowingsList() {
      return followings_;
    }
    /**
     * <code>repeated .boa.types.Person followings = 5;</code>
     */
    public java.util.List<? extends boa.types.Shared.PersonOrBuilder> 
        getFollowingsOrBuilderList() {
      return followings_;
    }
    /**
     * <code>repeated .boa.types.Person followings = 5;</code>
     */
    public int getFollowingsCount() {
      return followings_.size();
    }
    /**
     * <code>repeated .boa.types.Person followings = 5;</code>
     */
    public boa.types.Shared.Person getFollowings(int index) {
      return followings_.get(index);
    }
    /**
     * <code>repeated .boa.types.Person followings = 5;</code>
     */
    public boa.types.Shared.PersonOrBuilder getFollowingsOrBuilder(
        int index) {
      return followings_.get(index);
    }

    // repeated string organizations = 6;
    public static final int ORGANIZATIONS_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList organizations_;
    /**
     * <code>repeated string organizations = 6;</code>
     */
    public java.util.List<java.lang.String>
        getOrganizationsList() {
      return organizations_;
    }
    /**
     * <code>repeated string organizations = 6;</code>
     */
    public int getOrganizationsCount() {
      return organizations_.size();
    }
    /**
     * <code>repeated string organizations = 6;</code>
     */
    public java.lang.String getOrganizations(int index) {
      return organizations_.get(index);
    }
    /**
     * <code>repeated string organizations = 6;</code>
     */
    public com.google.protobuf.ByteString
        getOrganizationsBytes(int index) {
      return organizations_.getByteString(index);
    }

    private void initFields() {
      username_ = "";
      realName_ = "";
      email_ = "";
      followers_ = java.util.Collections.emptyList();
      followings_ = java.util.Collections.emptyList();
      organizations_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUsername()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRealName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEmail()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getFollowersCount(); i++) {
        if (!getFollowers(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getFollowingsCount(); i++) {
        if (!getFollowings(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getRealNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getEmailBytes());
      }
      for (int i = 0; i < followers_.size(); i++) {
        output.writeMessage(4, followers_.get(i));
      }
      for (int i = 0; i < followings_.size(); i++) {
        output.writeMessage(5, followings_.get(i));
      }
      for (int i = 0; i < organizations_.size(); i++) {
        output.writeBytes(6, organizations_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getRealNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getEmailBytes());
      }
      for (int i = 0; i < followers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, followers_.get(i));
      }
      for (int i = 0; i < followings_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, followings_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < organizations_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(organizations_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getOrganizationsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static boa.types.Shared.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static boa.types.Shared.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static boa.types.Shared.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static boa.types.Shared.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static boa.types.Shared.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static boa.types.Shared.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static boa.types.Shared.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static boa.types.Shared.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static boa.types.Shared.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static boa.types.Shared.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(boa.types.Shared.Person prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code boa.types.Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements boa.types.Shared.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return boa.types.Shared.internal_static_boa_types_Person_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return boa.types.Shared.internal_static_boa_types_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                boa.types.Shared.Person.class, boa.types.Shared.Person.Builder.class);
      }

      // Construct using boa.types.Shared.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFollowersFieldBuilder();
          getFollowingsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        username_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        realName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (followersBuilder_ == null) {
          followers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          followersBuilder_.clear();
        }
        if (followingsBuilder_ == null) {
          followings_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          followingsBuilder_.clear();
        }
        organizations_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return boa.types.Shared.internal_static_boa_types_Person_descriptor;
      }

      public boa.types.Shared.Person getDefaultInstanceForType() {
        return boa.types.Shared.Person.getDefaultInstance();
      }

      public boa.types.Shared.Person build() {
        boa.types.Shared.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public boa.types.Shared.Person buildPartial() {
        boa.types.Shared.Person result = new boa.types.Shared.Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.username_ = username_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.realName_ = realName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.email_ = email_;
        if (followersBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            followers_ = java.util.Collections.unmodifiableList(followers_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.followers_ = followers_;
        } else {
          result.followers_ = followersBuilder_.build();
        }
        if (followingsBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            followings_ = java.util.Collections.unmodifiableList(followings_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.followings_ = followings_;
        } else {
          result.followings_ = followingsBuilder_.build();
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          organizations_ = new com.google.protobuf.UnmodifiableLazyStringList(
              organizations_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.organizations_ = organizations_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof boa.types.Shared.Person) {
          return mergeFrom((boa.types.Shared.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(boa.types.Shared.Person other) {
        if (other == boa.types.Shared.Person.getDefaultInstance()) return this;
        if (other.hasUsername()) {
          bitField0_ |= 0x00000001;
          username_ = other.username_;
          onChanged();
        }
        if (other.hasRealName()) {
          bitField0_ |= 0x00000002;
          realName_ = other.realName_;
          onChanged();
        }
        if (other.hasEmail()) {
          bitField0_ |= 0x00000004;
          email_ = other.email_;
          onChanged();
        }
        if (followersBuilder_ == null) {
          if (!other.followers_.isEmpty()) {
            if (followers_.isEmpty()) {
              followers_ = other.followers_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureFollowersIsMutable();
              followers_.addAll(other.followers_);
            }
            onChanged();
          }
        } else {
          if (!other.followers_.isEmpty()) {
            if (followersBuilder_.isEmpty()) {
              followersBuilder_.dispose();
              followersBuilder_ = null;
              followers_ = other.followers_;
              bitField0_ = (bitField0_ & ~0x00000008);
              followersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFollowersFieldBuilder() : null;
            } else {
              followersBuilder_.addAllMessages(other.followers_);
            }
          }
        }
        if (followingsBuilder_ == null) {
          if (!other.followings_.isEmpty()) {
            if (followings_.isEmpty()) {
              followings_ = other.followings_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureFollowingsIsMutable();
              followings_.addAll(other.followings_);
            }
            onChanged();
          }
        } else {
          if (!other.followings_.isEmpty()) {
            if (followingsBuilder_.isEmpty()) {
              followingsBuilder_.dispose();
              followingsBuilder_ = null;
              followings_ = other.followings_;
              bitField0_ = (bitField0_ & ~0x00000010);
              followingsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFollowingsFieldBuilder() : null;
            } else {
              followingsBuilder_.addAllMessages(other.followings_);
            }
          }
        }
        if (!other.organizations_.isEmpty()) {
          if (organizations_.isEmpty()) {
            organizations_ = other.organizations_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureOrganizationsIsMutable();
            organizations_.addAll(other.organizations_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUsername()) {
          
          return false;
        }
        if (!hasRealName()) {
          
          return false;
        }
        if (!hasEmail()) {
          
          return false;
        }
        for (int i = 0; i < getFollowersCount(); i++) {
          if (!getFollowers(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getFollowingsCount(); i++) {
          if (!getFollowings(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        boa.types.Shared.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (boa.types.Shared.Person) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string username = 1;
      private java.lang.Object username_ = "";
      /**
       * <code>required string username = 1;</code>
       */
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string username = 1;</code>
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string username = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string username = 1;</code>
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string username = 1;</code>
       */
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000001);
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <code>required string username = 1;</code>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        username_ = value;
        onChanged();
        return this;
      }

      // required string real_name = 2;
      private java.lang.Object realName_ = "";
      /**
       * <code>required string real_name = 2;</code>
       */
      public boolean hasRealName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string real_name = 2;</code>
       */
      public java.lang.String getRealName() {
        java.lang.Object ref = realName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          realName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string real_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRealNameBytes() {
        java.lang.Object ref = realName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          realName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string real_name = 2;</code>
       */
      public Builder setRealName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        realName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string real_name = 2;</code>
       */
      public Builder clearRealName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        realName_ = getDefaultInstance().getRealName();
        onChanged();
        return this;
      }
      /**
       * <code>required string real_name = 2;</code>
       */
      public Builder setRealNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        realName_ = value;
        onChanged();
        return this;
      }

      // required string email = 3;
      private java.lang.Object email_ = "";
      /**
       * <code>required string email = 3;</code>
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string email = 3;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string email = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string email = 3;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string email = 3;</code>
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000004);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>required string email = 3;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }

      // repeated .boa.types.Person followers = 4;
      private java.util.List<boa.types.Shared.Person> followers_ =
        java.util.Collections.emptyList();
      private void ensureFollowersIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          followers_ = new java.util.ArrayList<boa.types.Shared.Person>(followers_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          boa.types.Shared.Person, boa.types.Shared.Person.Builder, boa.types.Shared.PersonOrBuilder> followersBuilder_;

      /**
       * <code>repeated .boa.types.Person followers = 4;</code>
       */
      public java.util.List<boa.types.Shared.Person> getFollowersList() {
        if (followersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(followers_);
        } else {
          return followersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .boa.types.Person followers = 4;</code>
       */
      public int getFollowersCount() {
        if (followersBuilder_ == null) {
          return followers_.size();
        } else {
          return followersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .boa.types.Person followers = 4;</code>
       */
      public boa.types.Shared.Person getFollowers(int index) {
        if (followersBuilder_ == null) {
          return followers_.get(index);
        } else {
          return followersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .boa.types.Person followers = 4;</code>
       */
      public Builder setFollowers(
          int index, boa.types.Shared.Person value) {
        if (followersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFollowersIsMutable();
          followers_.set(index, value);
          onChanged();
        } else {
          followersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.Person followers = 4;</code>
       */
      public Builder setFollowers(
          int index, boa.types.Shared.Person.Builder builderForValue) {
        if (followersBuilder_ == null) {
          ensureFollowersIsMutable();
          followers_.set(index, builderForValue.build());
          onChanged();
        } else {
          followersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.Person followers = 4;</code>
       */
      public Builder addFollowers(boa.types.Shared.Person value) {
        if (followersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFollowersIsMutable();
          followers_.add(value);
          onChanged();
        } else {
          followersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.Person followers = 4;</code>
       */
      public Builder addFollowers(
          int index, boa.types.Shared.Person value) {
        if (followersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFollowersIsMutable();
          followers_.add(index, value);
          onChanged();
        } else {
          followersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.Person followers = 4;</code>
       */
      public Builder addFollowers(
          boa.types.Shared.Person.Builder builderForValue) {
        if (followersBuilder_ == null) {
          ensureFollowersIsMutable();
          followers_.add(builderForValue.build());
          onChanged();
        } else {
          followersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.Person followers = 4;</code>
       */
      public Builder addFollowers(
          int index, boa.types.Shared.Person.Builder builderForValue) {
        if (followersBuilder_ == null) {
          ensureFollowersIsMutable();
          followers_.add(index, builderForValue.build());
          onChanged();
        } else {
          followersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.Person followers = 4;</code>
       */
      public Builder addAllFollowers(
          java.lang.Iterable<? extends boa.types.Shared.Person> values) {
        if (followersBuilder_ == null) {
          ensureFollowersIsMutable();
          super.addAll(values, followers_);
          onChanged();
        } else {
          followersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.Person followers = 4;</code>
       */
      public Builder clearFollowers() {
        if (followersBuilder_ == null) {
          followers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          followersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.Person followers = 4;</code>
       */
      public Builder removeFollowers(int index) {
        if (followersBuilder_ == null) {
          ensureFollowersIsMutable();
          followers_.remove(index);
          onChanged();
        } else {
          followersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.Person followers = 4;</code>
       */
      public boa.types.Shared.Person.Builder getFollowersBuilder(
          int index) {
        return getFollowersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .boa.types.Person followers = 4;</code>
       */
      public boa.types.Shared.PersonOrBuilder getFollowersOrBuilder(
          int index) {
        if (followersBuilder_ == null) {
          return followers_.get(index);  } else {
          return followersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .boa.types.Person followers = 4;</code>
       */
      public java.util.List<? extends boa.types.Shared.PersonOrBuilder> 
           getFollowersOrBuilderList() {
        if (followersBuilder_ != null) {
          return followersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(followers_);
        }
      }
      /**
       * <code>repeated .boa.types.Person followers = 4;</code>
       */
      public boa.types.Shared.Person.Builder addFollowersBuilder() {
        return getFollowersFieldBuilder().addBuilder(
            boa.types.Shared.Person.getDefaultInstance());
      }
      /**
       * <code>repeated .boa.types.Person followers = 4;</code>
       */
      public boa.types.Shared.Person.Builder addFollowersBuilder(
          int index) {
        return getFollowersFieldBuilder().addBuilder(
            index, boa.types.Shared.Person.getDefaultInstance());
      }
      /**
       * <code>repeated .boa.types.Person followers = 4;</code>
       */
      public java.util.List<boa.types.Shared.Person.Builder> 
           getFollowersBuilderList() {
        return getFollowersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          boa.types.Shared.Person, boa.types.Shared.Person.Builder, boa.types.Shared.PersonOrBuilder> 
          getFollowersFieldBuilder() {
        if (followersBuilder_ == null) {
          followersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              boa.types.Shared.Person, boa.types.Shared.Person.Builder, boa.types.Shared.PersonOrBuilder>(
                  followers_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          followers_ = null;
        }
        return followersBuilder_;
      }

      // repeated .boa.types.Person followings = 5;
      private java.util.List<boa.types.Shared.Person> followings_ =
        java.util.Collections.emptyList();
      private void ensureFollowingsIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          followings_ = new java.util.ArrayList<boa.types.Shared.Person>(followings_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          boa.types.Shared.Person, boa.types.Shared.Person.Builder, boa.types.Shared.PersonOrBuilder> followingsBuilder_;

      /**
       * <code>repeated .boa.types.Person followings = 5;</code>
       */
      public java.util.List<boa.types.Shared.Person> getFollowingsList() {
        if (followingsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(followings_);
        } else {
          return followingsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .boa.types.Person followings = 5;</code>
       */
      public int getFollowingsCount() {
        if (followingsBuilder_ == null) {
          return followings_.size();
        } else {
          return followingsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .boa.types.Person followings = 5;</code>
       */
      public boa.types.Shared.Person getFollowings(int index) {
        if (followingsBuilder_ == null) {
          return followings_.get(index);
        } else {
          return followingsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .boa.types.Person followings = 5;</code>
       */
      public Builder setFollowings(
          int index, boa.types.Shared.Person value) {
        if (followingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFollowingsIsMutable();
          followings_.set(index, value);
          onChanged();
        } else {
          followingsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.Person followings = 5;</code>
       */
      public Builder setFollowings(
          int index, boa.types.Shared.Person.Builder builderForValue) {
        if (followingsBuilder_ == null) {
          ensureFollowingsIsMutable();
          followings_.set(index, builderForValue.build());
          onChanged();
        } else {
          followingsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.Person followings = 5;</code>
       */
      public Builder addFollowings(boa.types.Shared.Person value) {
        if (followingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFollowingsIsMutable();
          followings_.add(value);
          onChanged();
        } else {
          followingsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.Person followings = 5;</code>
       */
      public Builder addFollowings(
          int index, boa.types.Shared.Person value) {
        if (followingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFollowingsIsMutable();
          followings_.add(index, value);
          onChanged();
        } else {
          followingsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.Person followings = 5;</code>
       */
      public Builder addFollowings(
          boa.types.Shared.Person.Builder builderForValue) {
        if (followingsBuilder_ == null) {
          ensureFollowingsIsMutable();
          followings_.add(builderForValue.build());
          onChanged();
        } else {
          followingsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.Person followings = 5;</code>
       */
      public Builder addFollowings(
          int index, boa.types.Shared.Person.Builder builderForValue) {
        if (followingsBuilder_ == null) {
          ensureFollowingsIsMutable();
          followings_.add(index, builderForValue.build());
          onChanged();
        } else {
          followingsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.Person followings = 5;</code>
       */
      public Builder addAllFollowings(
          java.lang.Iterable<? extends boa.types.Shared.Person> values) {
        if (followingsBuilder_ == null) {
          ensureFollowingsIsMutable();
          super.addAll(values, followings_);
          onChanged();
        } else {
          followingsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.Person followings = 5;</code>
       */
      public Builder clearFollowings() {
        if (followingsBuilder_ == null) {
          followings_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          followingsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.Person followings = 5;</code>
       */
      public Builder removeFollowings(int index) {
        if (followingsBuilder_ == null) {
          ensureFollowingsIsMutable();
          followings_.remove(index);
          onChanged();
        } else {
          followingsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.Person followings = 5;</code>
       */
      public boa.types.Shared.Person.Builder getFollowingsBuilder(
          int index) {
        return getFollowingsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .boa.types.Person followings = 5;</code>
       */
      public boa.types.Shared.PersonOrBuilder getFollowingsOrBuilder(
          int index) {
        if (followingsBuilder_ == null) {
          return followings_.get(index);  } else {
          return followingsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .boa.types.Person followings = 5;</code>
       */
      public java.util.List<? extends boa.types.Shared.PersonOrBuilder> 
           getFollowingsOrBuilderList() {
        if (followingsBuilder_ != null) {
          return followingsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(followings_);
        }
      }
      /**
       * <code>repeated .boa.types.Person followings = 5;</code>
       */
      public boa.types.Shared.Person.Builder addFollowingsBuilder() {
        return getFollowingsFieldBuilder().addBuilder(
            boa.types.Shared.Person.getDefaultInstance());
      }
      /**
       * <code>repeated .boa.types.Person followings = 5;</code>
       */
      public boa.types.Shared.Person.Builder addFollowingsBuilder(
          int index) {
        return getFollowingsFieldBuilder().addBuilder(
            index, boa.types.Shared.Person.getDefaultInstance());
      }
      /**
       * <code>repeated .boa.types.Person followings = 5;</code>
       */
      public java.util.List<boa.types.Shared.Person.Builder> 
           getFollowingsBuilderList() {
        return getFollowingsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          boa.types.Shared.Person, boa.types.Shared.Person.Builder, boa.types.Shared.PersonOrBuilder> 
          getFollowingsFieldBuilder() {
        if (followingsBuilder_ == null) {
          followingsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              boa.types.Shared.Person, boa.types.Shared.Person.Builder, boa.types.Shared.PersonOrBuilder>(
                  followings_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          followings_ = null;
        }
        return followingsBuilder_;
      }

      // repeated string organizations = 6;
      private com.google.protobuf.LazyStringList organizations_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureOrganizationsIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          organizations_ = new com.google.protobuf.LazyStringArrayList(organizations_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated string organizations = 6;</code>
       */
      public java.util.List<java.lang.String>
          getOrganizationsList() {
        return java.util.Collections.unmodifiableList(organizations_);
      }
      /**
       * <code>repeated string organizations = 6;</code>
       */
      public int getOrganizationsCount() {
        return organizations_.size();
      }
      /**
       * <code>repeated string organizations = 6;</code>
       */
      public java.lang.String getOrganizations(int index) {
        return organizations_.get(index);
      }
      /**
       * <code>repeated string organizations = 6;</code>
       */
      public com.google.protobuf.ByteString
          getOrganizationsBytes(int index) {
        return organizations_.getByteString(index);
      }
      /**
       * <code>repeated string organizations = 6;</code>
       */
      public Builder setOrganizations(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureOrganizationsIsMutable();
        organizations_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string organizations = 6;</code>
       */
      public Builder addOrganizations(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureOrganizationsIsMutable();
        organizations_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string organizations = 6;</code>
       */
      public Builder addAllOrganizations(
          java.lang.Iterable<java.lang.String> values) {
        ensureOrganizationsIsMutable();
        super.addAll(values, organizations_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string organizations = 6;</code>
       */
      public Builder clearOrganizations() {
        organizations_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string organizations = 6;</code>
       */
      public Builder addOrganizationsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureOrganizationsIsMutable();
        organizations_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:boa.types.Person)
    }

    static {
      defaultInstance = new Person(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:boa.types.Person)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_boa_types_Person_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_boa_types_Person_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014shared.proto\022\tboa.types\"\240\001\n\006Person\022\020\n\010" +
      "username\030\001 \002(\t\022\021\n\treal_name\030\002 \002(\t\022\r\n\005ema" +
      "il\030\003 \002(\t\022$\n\tfollowers\030\004 \003(\0132\021.boa.types." +
      "Person\022%\n\nfollowings\030\005 \003(\0132\021.boa.types.P" +
      "erson\022\025\n\rorganizations\030\006 \003(\t*2\n\nChangeKi" +
      "nd\022\t\n\005ADDED\020\001\022\013\n\007DELETED\020\002\022\014\n\010MODIFIED\020\003" +
      "B\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_boa_types_Person_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_boa_types_Person_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_boa_types_Person_descriptor,
              new java.lang.String[] { "Username", "RealName", "Email", "Followers", "Followings", "Organizations", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
