// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bio.proto

package boa.bio.types;

public final class Bio {
  private Bio() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BioDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string Experiment_Accession = 1;
    /**
     * <code>required string Experiment_Accession = 1;</code>
     */
    boolean hasExperimentAccession();
    /**
     * <code>required string Experiment_Accession = 1;</code>
     */
    String getExperimentAccession();
    /**
     * <code>required string Experiment_Accession = 1;</code>
     */
    com.google.protobuf.ByteString
        getExperimentAccessionBytes();

    // required string Experiment_Title = 2;
    /**
     * <code>required string Experiment_Title = 2;</code>
     */
    boolean hasExperimentTitle();
    /**
     * <code>required string Experiment_Title = 2;</code>
     */
    String getExperimentTitle();
    /**
     * <code>required string Experiment_Title = 2;</code>
     */
    com.google.protobuf.ByteString
        getExperimentTitleBytes();

    // required string Organism_Name = 3;
    /**
     * <code>required string Organism_Name = 3;</code>
     */
    boolean hasOrganismName();
    /**
     * <code>required string Organism_Name = 3;</code>
     */
    String getOrganismName();
    /**
     * <code>required string Organism_Name = 3;</code>
     */
    com.google.protobuf.ByteString
        getOrganismNameBytes();

    // required string Instrument = 4;
    /**
     * <code>required string Instrument = 4;</code>
     */
    boolean hasInstrument();
    /**
     * <code>required string Instrument = 4;</code>
     */
    String getInstrument();
    /**
     * <code>required string Instrument = 4;</code>
     */
    com.google.protobuf.ByteString
        getInstrumentBytes();

    // optional string Submitter = 5;
    /**
     * <code>optional string Submitter = 5;</code>
     */
    boolean hasSubmitter();
    /**
     * <code>optional string Submitter = 5;</code>
     */
    String getSubmitter();
    /**
     * <code>optional string Submitter = 5;</code>
     */
    com.google.protobuf.ByteString
        getSubmitterBytes();

    // required string Study_Accession = 6;
    /**
     * <code>required string Study_Accession = 6;</code>
     */
    boolean hasStudyAccession();
    /**
     * <code>required string Study_Accession = 6;</code>
     */
    String getStudyAccession();
    /**
     * <code>required string Study_Accession = 6;</code>
     */
    com.google.protobuf.ByteString
        getStudyAccessionBytes();

    // required string Study_Title = 7;
    /**
     * <code>required string Study_Title = 7;</code>
     */
    boolean hasStudyTitle();
    /**
     * <code>required string Study_Title = 7;</code>
     */
    String getStudyTitle();
    /**
     * <code>required string Study_Title = 7;</code>
     */
    com.google.protobuf.ByteString
        getStudyTitleBytes();

    // required string Sample_Accession = 8;
    /**
     * <code>required string Sample_Accession = 8;</code>
     */
    boolean hasSampleAccession();
    /**
     * <code>required string Sample_Accession = 8;</code>
     */
    String getSampleAccession();
    /**
     * <code>required string Sample_Accession = 8;</code>
     */
    com.google.protobuf.ByteString
        getSampleAccessionBytes();

    // optional string Sample_Title = 9;
    /**
     * <code>optional string Sample_Title = 9;</code>
     */
    boolean hasSampleTitle();
    /**
     * <code>optional string Sample_Title = 9;</code>
     */
    String getSampleTitle();
    /**
     * <code>optional string Sample_Title = 9;</code>
     */
    com.google.protobuf.ByteString
        getSampleTitleBytes();

    // required float Total_Size = 10;
    /**
     * <code>required float Total_Size = 10;</code>
     */
    boolean hasTotalSize();
    /**
     * <code>required float Total_Size = 10;</code>
     */
    float getTotalSize();

    // required int64 Total_RUNs = 11;
    /**
     * <code>required int64 Total_RUNs = 11;</code>
     */
    boolean hasTotalRUNs();
    /**
     * <code>required int64 Total_RUNs = 11;</code>
     */
    long getTotalRUNs();

    // required int64 Total_Spots = 12;
    /**
     * <code>required int64 Total_Spots = 12;</code>
     */
    boolean hasTotalSpots();
    /**
     * <code>required int64 Total_Spots = 12;</code>
     */
    long getTotalSpots();

    // required int64 Total_Bases = 13;
    /**
     * <code>required int64 Total_Bases = 13;</code>
     */
    boolean hasTotalBases();
    /**
     * <code>required int64 Total_Bases = 13;</code>
     */
    long getTotalBases();

    // required string Library_Name = 14;
    /**
     * <code>required string Library_Name = 14;</code>
     */
    boolean hasLibraryName();
    /**
     * <code>required string Library_Name = 14;</code>
     */
    String getLibraryName();
    /**
     * <code>required string Library_Name = 14;</code>
     */
    com.google.protobuf.ByteString
        getLibraryNameBytes();

    // required string Library_Strategy = 15;
    /**
     * <code>required string Library_Strategy = 15;</code>
     */
    boolean hasLibraryStrategy();
    /**
     * <code>required string Library_Strategy = 15;</code>
     */
    String getLibraryStrategy();
    /**
     * <code>required string Library_Strategy = 15;</code>
     */
    com.google.protobuf.ByteString
        getLibraryStrategyBytes();

    // required string Library_Source = 16;
    /**
     * <code>required string Library_Source = 16;</code>
     */
    boolean hasLibrarySource();
    /**
     * <code>required string Library_Source = 16;</code>
     */
    String getLibrarySource();
    /**
     * <code>required string Library_Source = 16;</code>
     */
    com.google.protobuf.ByteString
        getLibrarySourceBytes();

    // required string Library_Selection = 17;
    /**
     * <code>required string Library_Selection = 17;</code>
     */
    boolean hasLibrarySelection();
    /**
     * <code>required string Library_Selection = 17;</code>
     */
    String getLibrarySelection();
    /**
     * <code>required string Library_Selection = 17;</code>
     */
    com.google.protobuf.ByteString
        getLibrarySelectionBytes();
  }
  /**
   * Protobuf type {@code boa.bio.types.BioData}
   */
  public static final class BioData extends
      com.google.protobuf.GeneratedMessage
      implements BioDataOrBuilder {
    // Use BioData.newBuilder() to construct.
    private BioData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BioData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BioData defaultInstance;
    public static BioData getDefaultInstance() {
      return defaultInstance;
    }

    public BioData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BioData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              experimentAccession_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              experimentTitle_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              organismName_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              instrument_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              submitter_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              studyAccession_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              studyTitle_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              sampleAccession_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              sampleTitle_ = input.readBytes();
              break;
            }
            case 85: {
              bitField0_ |= 0x00000200;
              totalSize_ = input.readFloat();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              totalRUNs_ = input.readInt64();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              totalSpots_ = input.readInt64();
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              totalBases_ = input.readInt64();
              break;
            }
            case 114: {
              bitField0_ |= 0x00002000;
              libraryName_ = input.readBytes();
              break;
            }
            case 122: {
              bitField0_ |= 0x00004000;
              libraryStrategy_ = input.readBytes();
              break;
            }
            case 130: {
              bitField0_ |= 0x00008000;
              librarySource_ = input.readBytes();
              break;
            }
            case 138: {
              bitField0_ |= 0x00010000;
              librarySelection_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Bio.internal_static_boa_bio_types_BioData_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Bio.internal_static_boa_bio_types_BioData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BioData.class, Builder.class);
    }

    public static com.google.protobuf.Parser<BioData> PARSER =
        new com.google.protobuf.AbstractParser<BioData>() {
      public BioData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BioData(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<BioData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string Experiment_Accession = 1;
    public static final int EXPERIMENT_ACCESSION_FIELD_NUMBER = 1;
    private Object experimentAccession_;
    /**
     * <code>required string Experiment_Accession = 1;</code>
     */
    public boolean hasExperimentAccession() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string Experiment_Accession = 1;</code>
     */
    public String getExperimentAccession() {
      Object ref = experimentAccession_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          experimentAccession_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string Experiment_Accession = 1;</code>
     */
    public com.google.protobuf.ByteString
        getExperimentAccessionBytes() {
      Object ref = experimentAccession_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        experimentAccession_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string Experiment_Title = 2;
    public static final int EXPERIMENT_TITLE_FIELD_NUMBER = 2;
    private Object experimentTitle_;
    /**
     * <code>required string Experiment_Title = 2;</code>
     */
    public boolean hasExperimentTitle() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string Experiment_Title = 2;</code>
     */
    public String getExperimentTitle() {
      Object ref = experimentTitle_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          experimentTitle_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string Experiment_Title = 2;</code>
     */
    public com.google.protobuf.ByteString
        getExperimentTitleBytes() {
      Object ref = experimentTitle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        experimentTitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string Organism_Name = 3;
    public static final int ORGANISM_NAME_FIELD_NUMBER = 3;
    private Object organismName_;
    /**
     * <code>required string Organism_Name = 3;</code>
     */
    public boolean hasOrganismName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string Organism_Name = 3;</code>
     */
    public String getOrganismName() {
      Object ref = organismName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          organismName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string Organism_Name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getOrganismNameBytes() {
      Object ref = organismName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        organismName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string Instrument = 4;
    public static final int INSTRUMENT_FIELD_NUMBER = 4;
    private Object instrument_;
    /**
     * <code>required string Instrument = 4;</code>
     */
    public boolean hasInstrument() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string Instrument = 4;</code>
     */
    public String getInstrument() {
      Object ref = instrument_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          instrument_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string Instrument = 4;</code>
     */
    public com.google.protobuf.ByteString
        getInstrumentBytes() {
      Object ref = instrument_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        instrument_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string Submitter = 5;
    public static final int SUBMITTER_FIELD_NUMBER = 5;
    private Object submitter_;
    /**
     * <code>optional string Submitter = 5;</code>
     */
    public boolean hasSubmitter() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string Submitter = 5;</code>
     */
    public String getSubmitter() {
      Object ref = submitter_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          submitter_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string Submitter = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSubmitterBytes() {
      Object ref = submitter_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        submitter_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string Study_Accession = 6;
    public static final int STUDY_ACCESSION_FIELD_NUMBER = 6;
    private Object studyAccession_;
    /**
     * <code>required string Study_Accession = 6;</code>
     */
    public boolean hasStudyAccession() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string Study_Accession = 6;</code>
     */
    public String getStudyAccession() {
      Object ref = studyAccession_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          studyAccession_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string Study_Accession = 6;</code>
     */
    public com.google.protobuf.ByteString
        getStudyAccessionBytes() {
      Object ref = studyAccession_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        studyAccession_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string Study_Title = 7;
    public static final int STUDY_TITLE_FIELD_NUMBER = 7;
    private Object studyTitle_;
    /**
     * <code>required string Study_Title = 7;</code>
     */
    public boolean hasStudyTitle() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required string Study_Title = 7;</code>
     */
    public String getStudyTitle() {
      Object ref = studyTitle_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          studyTitle_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string Study_Title = 7;</code>
     */
    public com.google.protobuf.ByteString
        getStudyTitleBytes() {
      Object ref = studyTitle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        studyTitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string Sample_Accession = 8;
    public static final int SAMPLE_ACCESSION_FIELD_NUMBER = 8;
    private Object sampleAccession_;
    /**
     * <code>required string Sample_Accession = 8;</code>
     */
    public boolean hasSampleAccession() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required string Sample_Accession = 8;</code>
     */
    public String getSampleAccession() {
      Object ref = sampleAccession_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sampleAccession_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string Sample_Accession = 8;</code>
     */
    public com.google.protobuf.ByteString
        getSampleAccessionBytes() {
      Object ref = sampleAccession_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sampleAccession_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string Sample_Title = 9;
    public static final int SAMPLE_TITLE_FIELD_NUMBER = 9;
    private Object sampleTitle_;
    /**
     * <code>optional string Sample_Title = 9;</code>
     */
    public boolean hasSampleTitle() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string Sample_Title = 9;</code>
     */
    public String getSampleTitle() {
      Object ref = sampleTitle_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sampleTitle_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string Sample_Title = 9;</code>
     */
    public com.google.protobuf.ByteString
        getSampleTitleBytes() {
      Object ref = sampleTitle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sampleTitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required float Total_Size = 10;
    public static final int TOTAL_SIZE_FIELD_NUMBER = 10;
    private float totalSize_;
    /**
     * <code>required float Total_Size = 10;</code>
     */
    public boolean hasTotalSize() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>required float Total_Size = 10;</code>
     */
    public float getTotalSize() {
      return totalSize_;
    }

    // required int64 Total_RUNs = 11;
    public static final int TOTAL_RUNS_FIELD_NUMBER = 11;
    private long totalRUNs_;
    /**
     * <code>required int64 Total_RUNs = 11;</code>
     */
    public boolean hasTotalRUNs() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>required int64 Total_RUNs = 11;</code>
     */
    public long getTotalRUNs() {
      return totalRUNs_;
    }

    // required int64 Total_Spots = 12;
    public static final int TOTAL_SPOTS_FIELD_NUMBER = 12;
    private long totalSpots_;
    /**
     * <code>required int64 Total_Spots = 12;</code>
     */
    public boolean hasTotalSpots() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>required int64 Total_Spots = 12;</code>
     */
    public long getTotalSpots() {
      return totalSpots_;
    }

    // required int64 Total_Bases = 13;
    public static final int TOTAL_BASES_FIELD_NUMBER = 13;
    private long totalBases_;
    /**
     * <code>required int64 Total_Bases = 13;</code>
     */
    public boolean hasTotalBases() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>required int64 Total_Bases = 13;</code>
     */
    public long getTotalBases() {
      return totalBases_;
    }

    // required string Library_Name = 14;
    public static final int LIBRARY_NAME_FIELD_NUMBER = 14;
    private Object libraryName_;
    /**
     * <code>required string Library_Name = 14;</code>
     */
    public boolean hasLibraryName() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>required string Library_Name = 14;</code>
     */
    public String getLibraryName() {
      Object ref = libraryName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          libraryName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string Library_Name = 14;</code>
     */
    public com.google.protobuf.ByteString
        getLibraryNameBytes() {
      Object ref = libraryName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        libraryName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string Library_Strategy = 15;
    public static final int LIBRARY_STRATEGY_FIELD_NUMBER = 15;
    private Object libraryStrategy_;
    /**
     * <code>required string Library_Strategy = 15;</code>
     */
    public boolean hasLibraryStrategy() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>required string Library_Strategy = 15;</code>
     */
    public String getLibraryStrategy() {
      Object ref = libraryStrategy_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          libraryStrategy_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string Library_Strategy = 15;</code>
     */
    public com.google.protobuf.ByteString
        getLibraryStrategyBytes() {
      Object ref = libraryStrategy_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        libraryStrategy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string Library_Source = 16;
    public static final int LIBRARY_SOURCE_FIELD_NUMBER = 16;
    private Object librarySource_;
    /**
     * <code>required string Library_Source = 16;</code>
     */
    public boolean hasLibrarySource() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    /**
     * <code>required string Library_Source = 16;</code>
     */
    public String getLibrarySource() {
      Object ref = librarySource_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          librarySource_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string Library_Source = 16;</code>
     */
    public com.google.protobuf.ByteString
        getLibrarySourceBytes() {
      Object ref = librarySource_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        librarySource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string Library_Selection = 17;
    public static final int LIBRARY_SELECTION_FIELD_NUMBER = 17;
    private Object librarySelection_;
    /**
     * <code>required string Library_Selection = 17;</code>
     */
    public boolean hasLibrarySelection() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    /**
     * <code>required string Library_Selection = 17;</code>
     */
    public String getLibrarySelection() {
      Object ref = librarySelection_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          librarySelection_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string Library_Selection = 17;</code>
     */
    public com.google.protobuf.ByteString
        getLibrarySelectionBytes() {
      Object ref = librarySelection_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        librarySelection_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      experimentAccession_ = "";
      experimentTitle_ = "";
      organismName_ = "";
      instrument_ = "";
      submitter_ = "";
      studyAccession_ = "";
      studyTitle_ = "";
      sampleAccession_ = "";
      sampleTitle_ = "";
      totalSize_ = 0F;
      totalRUNs_ = 0L;
      totalSpots_ = 0L;
      totalBases_ = 0L;
      libraryName_ = "";
      libraryStrategy_ = "";
      librarySource_ = "";
      librarySelection_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasExperimentAccession()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasExperimentTitle()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOrganismName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasInstrument()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStudyAccession()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStudyTitle()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSampleAccession()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTotalSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTotalRUNs()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTotalSpots()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTotalBases()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLibraryName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLibraryStrategy()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLibrarySource()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLibrarySelection()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getExperimentAccessionBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getExperimentTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getOrganismNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getInstrumentBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getSubmitterBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getStudyAccessionBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getStudyTitleBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getSampleAccessionBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getSampleTitleBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeFloat(10, totalSize_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt64(11, totalRUNs_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt64(12, totalSpots_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeInt64(13, totalBases_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeBytes(14, getLibraryNameBytes());
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeBytes(15, getLibraryStrategyBytes());
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeBytes(16, getLibrarySourceBytes());
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        output.writeBytes(17, getLibrarySelectionBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getExperimentAccessionBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getExperimentTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getOrganismNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getInstrumentBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getSubmitterBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getStudyAccessionBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getStudyTitleBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getSampleAccessionBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getSampleTitleBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(10, totalSize_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(11, totalRUNs_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(12, totalSpots_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(13, totalBases_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(14, getLibraryNameBytes());
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(15, getLibraryStrategyBytes());
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(16, getLibrarySourceBytes());
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(17, getLibrarySelectionBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static BioData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BioData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BioData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BioData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BioData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static BioData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static BioData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static BioData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static BioData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static BioData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(BioData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code boa.bio.types.BioData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements BioDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Bio.internal_static_boa_bio_types_BioData_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Bio.internal_static_boa_bio_types_BioData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BioData.class, Builder.class);
      }

      // Construct using boa.bio.types.Bio.BioData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        experimentAccession_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        experimentTitle_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        organismName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        instrument_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        submitter_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        studyAccession_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        studyTitle_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        sampleAccession_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        sampleTitle_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        totalSize_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000200);
        totalRUNs_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000400);
        totalSpots_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000800);
        totalBases_ = 0L;
        bitField0_ = (bitField0_ & ~0x00001000);
        libraryName_ = "";
        bitField0_ = (bitField0_ & ~0x00002000);
        libraryStrategy_ = "";
        bitField0_ = (bitField0_ & ~0x00004000);
        librarySource_ = "";
        bitField0_ = (bitField0_ & ~0x00008000);
        librarySelection_ = "";
        bitField0_ = (bitField0_ & ~0x00010000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Bio.internal_static_boa_bio_types_BioData_descriptor;
      }

      public BioData getDefaultInstanceForType() {
        return BioData.getDefaultInstance();
      }

      public BioData build() {
        BioData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public BioData buildPartial() {
        BioData result = new BioData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.experimentAccession_ = experimentAccession_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.experimentTitle_ = experimentTitle_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.organismName_ = organismName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.instrument_ = instrument_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.submitter_ = submitter_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.studyAccession_ = studyAccession_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.studyTitle_ = studyTitle_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.sampleAccession_ = sampleAccession_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.sampleTitle_ = sampleTitle_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.totalSize_ = totalSize_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.totalRUNs_ = totalRUNs_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.totalSpots_ = totalSpots_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.totalBases_ = totalBases_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.libraryName_ = libraryName_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.libraryStrategy_ = libraryStrategy_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.librarySource_ = librarySource_;
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00010000;
        }
        result.librarySelection_ = librarySelection_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BioData) {
          return mergeFrom((BioData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BioData other) {
        if (other == BioData.getDefaultInstance()) return this;
        if (other.hasExperimentAccession()) {
          bitField0_ |= 0x00000001;
          experimentAccession_ = other.experimentAccession_;
          onChanged();
        }
        if (other.hasExperimentTitle()) {
          bitField0_ |= 0x00000002;
          experimentTitle_ = other.experimentTitle_;
          onChanged();
        }
        if (other.hasOrganismName()) {
          bitField0_ |= 0x00000004;
          organismName_ = other.organismName_;
          onChanged();
        }
        if (other.hasInstrument()) {
          bitField0_ |= 0x00000008;
          instrument_ = other.instrument_;
          onChanged();
        }
        if (other.hasSubmitter()) {
          bitField0_ |= 0x00000010;
          submitter_ = other.submitter_;
          onChanged();
        }
        if (other.hasStudyAccession()) {
          bitField0_ |= 0x00000020;
          studyAccession_ = other.studyAccession_;
          onChanged();
        }
        if (other.hasStudyTitle()) {
          bitField0_ |= 0x00000040;
          studyTitle_ = other.studyTitle_;
          onChanged();
        }
        if (other.hasSampleAccession()) {
          bitField0_ |= 0x00000080;
          sampleAccession_ = other.sampleAccession_;
          onChanged();
        }
        if (other.hasSampleTitle()) {
          bitField0_ |= 0x00000100;
          sampleTitle_ = other.sampleTitle_;
          onChanged();
        }
        if (other.hasTotalSize()) {
          setTotalSize(other.getTotalSize());
        }
        if (other.hasTotalRUNs()) {
          setTotalRUNs(other.getTotalRUNs());
        }
        if (other.hasTotalSpots()) {
          setTotalSpots(other.getTotalSpots());
        }
        if (other.hasTotalBases()) {
          setTotalBases(other.getTotalBases());
        }
        if (other.hasLibraryName()) {
          bitField0_ |= 0x00002000;
          libraryName_ = other.libraryName_;
          onChanged();
        }
        if (other.hasLibraryStrategy()) {
          bitField0_ |= 0x00004000;
          libraryStrategy_ = other.libraryStrategy_;
          onChanged();
        }
        if (other.hasLibrarySource()) {
          bitField0_ |= 0x00008000;
          librarySource_ = other.librarySource_;
          onChanged();
        }
        if (other.hasLibrarySelection()) {
          bitField0_ |= 0x00010000;
          librarySelection_ = other.librarySelection_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasExperimentAccession()) {
          
          return false;
        }
        if (!hasExperimentTitle()) {
          
          return false;
        }
        if (!hasOrganismName()) {
          
          return false;
        }
        if (!hasInstrument()) {
          
          return false;
        }
        if (!hasStudyAccession()) {
          
          return false;
        }
        if (!hasStudyTitle()) {
          
          return false;
        }
        if (!hasSampleAccession()) {
          
          return false;
        }
        if (!hasTotalSize()) {
          
          return false;
        }
        if (!hasTotalRUNs()) {
          
          return false;
        }
        if (!hasTotalSpots()) {
          
          return false;
        }
        if (!hasTotalBases()) {
          
          return false;
        }
        if (!hasLibraryName()) {
          
          return false;
        }
        if (!hasLibraryStrategy()) {
          
          return false;
        }
        if (!hasLibrarySource()) {
          
          return false;
        }
        if (!hasLibrarySelection()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BioData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BioData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string Experiment_Accession = 1;
      private Object experimentAccession_ = "";
      /**
       * <code>required string Experiment_Accession = 1;</code>
       */
      public boolean hasExperimentAccession() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string Experiment_Accession = 1;</code>
       */
      public String getExperimentAccession() {
        Object ref = experimentAccession_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          experimentAccession_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string Experiment_Accession = 1;</code>
       */
      public com.google.protobuf.ByteString
          getExperimentAccessionBytes() {
        Object ref = experimentAccession_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          experimentAccession_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string Experiment_Accession = 1;</code>
       */
      public Builder setExperimentAccession(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        experimentAccession_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string Experiment_Accession = 1;</code>
       */
      public Builder clearExperimentAccession() {
        bitField0_ = (bitField0_ & ~0x00000001);
        experimentAccession_ = getDefaultInstance().getExperimentAccession();
        onChanged();
        return this;
      }
      /**
       * <code>required string Experiment_Accession = 1;</code>
       */
      public Builder setExperimentAccessionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        experimentAccession_ = value;
        onChanged();
        return this;
      }

      // required string Experiment_Title = 2;
      private Object experimentTitle_ = "";
      /**
       * <code>required string Experiment_Title = 2;</code>
       */
      public boolean hasExperimentTitle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string Experiment_Title = 2;</code>
       */
      public String getExperimentTitle() {
        Object ref = experimentTitle_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          experimentTitle_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string Experiment_Title = 2;</code>
       */
      public com.google.protobuf.ByteString
          getExperimentTitleBytes() {
        Object ref = experimentTitle_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          experimentTitle_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string Experiment_Title = 2;</code>
       */
      public Builder setExperimentTitle(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        experimentTitle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string Experiment_Title = 2;</code>
       */
      public Builder clearExperimentTitle() {
        bitField0_ = (bitField0_ & ~0x00000002);
        experimentTitle_ = getDefaultInstance().getExperimentTitle();
        onChanged();
        return this;
      }
      /**
       * <code>required string Experiment_Title = 2;</code>
       */
      public Builder setExperimentTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        experimentTitle_ = value;
        onChanged();
        return this;
      }

      // required string Organism_Name = 3;
      private Object organismName_ = "";
      /**
       * <code>required string Organism_Name = 3;</code>
       */
      public boolean hasOrganismName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string Organism_Name = 3;</code>
       */
      public String getOrganismName() {
        Object ref = organismName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          organismName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string Organism_Name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getOrganismNameBytes() {
        Object ref = organismName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          organismName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string Organism_Name = 3;</code>
       */
      public Builder setOrganismName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        organismName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string Organism_Name = 3;</code>
       */
      public Builder clearOrganismName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        organismName_ = getDefaultInstance().getOrganismName();
        onChanged();
        return this;
      }
      /**
       * <code>required string Organism_Name = 3;</code>
       */
      public Builder setOrganismNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        organismName_ = value;
        onChanged();
        return this;
      }

      // required string Instrument = 4;
      private Object instrument_ = "";
      /**
       * <code>required string Instrument = 4;</code>
       */
      public boolean hasInstrument() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string Instrument = 4;</code>
       */
      public String getInstrument() {
        Object ref = instrument_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          instrument_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string Instrument = 4;</code>
       */
      public com.google.protobuf.ByteString
          getInstrumentBytes() {
        Object ref = instrument_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          instrument_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string Instrument = 4;</code>
       */
      public Builder setInstrument(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        instrument_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string Instrument = 4;</code>
       */
      public Builder clearInstrument() {
        bitField0_ = (bitField0_ & ~0x00000008);
        instrument_ = getDefaultInstance().getInstrument();
        onChanged();
        return this;
      }
      /**
       * <code>required string Instrument = 4;</code>
       */
      public Builder setInstrumentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        instrument_ = value;
        onChanged();
        return this;
      }

      // optional string Submitter = 5;
      private Object submitter_ = "";
      /**
       * <code>optional string Submitter = 5;</code>
       */
      public boolean hasSubmitter() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string Submitter = 5;</code>
       */
      public String getSubmitter() {
        Object ref = submitter_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          submitter_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string Submitter = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSubmitterBytes() {
        Object ref = submitter_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          submitter_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string Submitter = 5;</code>
       */
      public Builder setSubmitter(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        submitter_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string Submitter = 5;</code>
       */
      public Builder clearSubmitter() {
        bitField0_ = (bitField0_ & ~0x00000010);
        submitter_ = getDefaultInstance().getSubmitter();
        onChanged();
        return this;
      }
      /**
       * <code>optional string Submitter = 5;</code>
       */
      public Builder setSubmitterBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        submitter_ = value;
        onChanged();
        return this;
      }

      // required string Study_Accession = 6;
      private Object studyAccession_ = "";
      /**
       * <code>required string Study_Accession = 6;</code>
       */
      public boolean hasStudyAccession() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string Study_Accession = 6;</code>
       */
      public String getStudyAccession() {
        Object ref = studyAccession_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          studyAccession_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string Study_Accession = 6;</code>
       */
      public com.google.protobuf.ByteString
          getStudyAccessionBytes() {
        Object ref = studyAccession_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          studyAccession_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string Study_Accession = 6;</code>
       */
      public Builder setStudyAccession(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        studyAccession_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string Study_Accession = 6;</code>
       */
      public Builder clearStudyAccession() {
        bitField0_ = (bitField0_ & ~0x00000020);
        studyAccession_ = getDefaultInstance().getStudyAccession();
        onChanged();
        return this;
      }
      /**
       * <code>required string Study_Accession = 6;</code>
       */
      public Builder setStudyAccessionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        studyAccession_ = value;
        onChanged();
        return this;
      }

      // required string Study_Title = 7;
      private Object studyTitle_ = "";
      /**
       * <code>required string Study_Title = 7;</code>
       */
      public boolean hasStudyTitle() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required string Study_Title = 7;</code>
       */
      public String getStudyTitle() {
        Object ref = studyTitle_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          studyTitle_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string Study_Title = 7;</code>
       */
      public com.google.protobuf.ByteString
          getStudyTitleBytes() {
        Object ref = studyTitle_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          studyTitle_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string Study_Title = 7;</code>
       */
      public Builder setStudyTitle(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        studyTitle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string Study_Title = 7;</code>
       */
      public Builder clearStudyTitle() {
        bitField0_ = (bitField0_ & ~0x00000040);
        studyTitle_ = getDefaultInstance().getStudyTitle();
        onChanged();
        return this;
      }
      /**
       * <code>required string Study_Title = 7;</code>
       */
      public Builder setStudyTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        studyTitle_ = value;
        onChanged();
        return this;
      }

      // required string Sample_Accession = 8;
      private Object sampleAccession_ = "";
      /**
       * <code>required string Sample_Accession = 8;</code>
       */
      public boolean hasSampleAccession() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required string Sample_Accession = 8;</code>
       */
      public String getSampleAccession() {
        Object ref = sampleAccession_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sampleAccession_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string Sample_Accession = 8;</code>
       */
      public com.google.protobuf.ByteString
          getSampleAccessionBytes() {
        Object ref = sampleAccession_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sampleAccession_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string Sample_Accession = 8;</code>
       */
      public Builder setSampleAccession(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        sampleAccession_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string Sample_Accession = 8;</code>
       */
      public Builder clearSampleAccession() {
        bitField0_ = (bitField0_ & ~0x00000080);
        sampleAccession_ = getDefaultInstance().getSampleAccession();
        onChanged();
        return this;
      }
      /**
       * <code>required string Sample_Accession = 8;</code>
       */
      public Builder setSampleAccessionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        sampleAccession_ = value;
        onChanged();
        return this;
      }

      // optional string Sample_Title = 9;
      private Object sampleTitle_ = "";
      /**
       * <code>optional string Sample_Title = 9;</code>
       */
      public boolean hasSampleTitle() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string Sample_Title = 9;</code>
       */
      public String getSampleTitle() {
        Object ref = sampleTitle_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sampleTitle_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string Sample_Title = 9;</code>
       */
      public com.google.protobuf.ByteString
          getSampleTitleBytes() {
        Object ref = sampleTitle_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sampleTitle_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string Sample_Title = 9;</code>
       */
      public Builder setSampleTitle(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        sampleTitle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string Sample_Title = 9;</code>
       */
      public Builder clearSampleTitle() {
        bitField0_ = (bitField0_ & ~0x00000100);
        sampleTitle_ = getDefaultInstance().getSampleTitle();
        onChanged();
        return this;
      }
      /**
       * <code>optional string Sample_Title = 9;</code>
       */
      public Builder setSampleTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        sampleTitle_ = value;
        onChanged();
        return this;
      }

      // required float Total_Size = 10;
      private float totalSize_ ;
      /**
       * <code>required float Total_Size = 10;</code>
       */
      public boolean hasTotalSize() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>required float Total_Size = 10;</code>
       */
      public float getTotalSize() {
        return totalSize_;
      }
      /**
       * <code>required float Total_Size = 10;</code>
       */
      public Builder setTotalSize(float value) {
        bitField0_ |= 0x00000200;
        totalSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float Total_Size = 10;</code>
       */
      public Builder clearTotalSize() {
        bitField0_ = (bitField0_ & ~0x00000200);
        totalSize_ = 0F;
        onChanged();
        return this;
      }

      // required int64 Total_RUNs = 11;
      private long totalRUNs_ ;
      /**
       * <code>required int64 Total_RUNs = 11;</code>
       */
      public boolean hasTotalRUNs() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>required int64 Total_RUNs = 11;</code>
       */
      public long getTotalRUNs() {
        return totalRUNs_;
      }
      /**
       * <code>required int64 Total_RUNs = 11;</code>
       */
      public Builder setTotalRUNs(long value) {
        bitField0_ |= 0x00000400;
        totalRUNs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 Total_RUNs = 11;</code>
       */
      public Builder clearTotalRUNs() {
        bitField0_ = (bitField0_ & ~0x00000400);
        totalRUNs_ = 0L;
        onChanged();
        return this;
      }

      // required int64 Total_Spots = 12;
      private long totalSpots_ ;
      /**
       * <code>required int64 Total_Spots = 12;</code>
       */
      public boolean hasTotalSpots() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>required int64 Total_Spots = 12;</code>
       */
      public long getTotalSpots() {
        return totalSpots_;
      }
      /**
       * <code>required int64 Total_Spots = 12;</code>
       */
      public Builder setTotalSpots(long value) {
        bitField0_ |= 0x00000800;
        totalSpots_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 Total_Spots = 12;</code>
       */
      public Builder clearTotalSpots() {
        bitField0_ = (bitField0_ & ~0x00000800);
        totalSpots_ = 0L;
        onChanged();
        return this;
      }

      // required int64 Total_Bases = 13;
      private long totalBases_ ;
      /**
       * <code>required int64 Total_Bases = 13;</code>
       */
      public boolean hasTotalBases() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>required int64 Total_Bases = 13;</code>
       */
      public long getTotalBases() {
        return totalBases_;
      }
      /**
       * <code>required int64 Total_Bases = 13;</code>
       */
      public Builder setTotalBases(long value) {
        bitField0_ |= 0x00001000;
        totalBases_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 Total_Bases = 13;</code>
       */
      public Builder clearTotalBases() {
        bitField0_ = (bitField0_ & ~0x00001000);
        totalBases_ = 0L;
        onChanged();
        return this;
      }

      // required string Library_Name = 14;
      private Object libraryName_ = "";
      /**
       * <code>required string Library_Name = 14;</code>
       */
      public boolean hasLibraryName() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>required string Library_Name = 14;</code>
       */
      public String getLibraryName() {
        Object ref = libraryName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          libraryName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string Library_Name = 14;</code>
       */
      public com.google.protobuf.ByteString
          getLibraryNameBytes() {
        Object ref = libraryName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          libraryName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string Library_Name = 14;</code>
       */
      public Builder setLibraryName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00002000;
        libraryName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string Library_Name = 14;</code>
       */
      public Builder clearLibraryName() {
        bitField0_ = (bitField0_ & ~0x00002000);
        libraryName_ = getDefaultInstance().getLibraryName();
        onChanged();
        return this;
      }
      /**
       * <code>required string Library_Name = 14;</code>
       */
      public Builder setLibraryNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00002000;
        libraryName_ = value;
        onChanged();
        return this;
      }

      // required string Library_Strategy = 15;
      private Object libraryStrategy_ = "";
      /**
       * <code>required string Library_Strategy = 15;</code>
       */
      public boolean hasLibraryStrategy() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>required string Library_Strategy = 15;</code>
       */
      public String getLibraryStrategy() {
        Object ref = libraryStrategy_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          libraryStrategy_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string Library_Strategy = 15;</code>
       */
      public com.google.protobuf.ByteString
          getLibraryStrategyBytes() {
        Object ref = libraryStrategy_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          libraryStrategy_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string Library_Strategy = 15;</code>
       */
      public Builder setLibraryStrategy(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
        libraryStrategy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string Library_Strategy = 15;</code>
       */
      public Builder clearLibraryStrategy() {
        bitField0_ = (bitField0_ & ~0x00004000);
        libraryStrategy_ = getDefaultInstance().getLibraryStrategy();
        onChanged();
        return this;
      }
      /**
       * <code>required string Library_Strategy = 15;</code>
       */
      public Builder setLibraryStrategyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
        libraryStrategy_ = value;
        onChanged();
        return this;
      }

      // required string Library_Source = 16;
      private Object librarySource_ = "";
      /**
       * <code>required string Library_Source = 16;</code>
       */
      public boolean hasLibrarySource() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      /**
       * <code>required string Library_Source = 16;</code>
       */
      public String getLibrarySource() {
        Object ref = librarySource_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          librarySource_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string Library_Source = 16;</code>
       */
      public com.google.protobuf.ByteString
          getLibrarySourceBytes() {
        Object ref = librarySource_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          librarySource_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string Library_Source = 16;</code>
       */
      public Builder setLibrarySource(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00008000;
        librarySource_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string Library_Source = 16;</code>
       */
      public Builder clearLibrarySource() {
        bitField0_ = (bitField0_ & ~0x00008000);
        librarySource_ = getDefaultInstance().getLibrarySource();
        onChanged();
        return this;
      }
      /**
       * <code>required string Library_Source = 16;</code>
       */
      public Builder setLibrarySourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00008000;
        librarySource_ = value;
        onChanged();
        return this;
      }

      // required string Library_Selection = 17;
      private Object librarySelection_ = "";
      /**
       * <code>required string Library_Selection = 17;</code>
       */
      public boolean hasLibrarySelection() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      /**
       * <code>required string Library_Selection = 17;</code>
       */
      public String getLibrarySelection() {
        Object ref = librarySelection_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          librarySelection_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string Library_Selection = 17;</code>
       */
      public com.google.protobuf.ByteString
          getLibrarySelectionBytes() {
        Object ref = librarySelection_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          librarySelection_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string Library_Selection = 17;</code>
       */
      public Builder setLibrarySelection(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00010000;
        librarySelection_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string Library_Selection = 17;</code>
       */
      public Builder clearLibrarySelection() {
        bitField0_ = (bitField0_ & ~0x00010000);
        librarySelection_ = getDefaultInstance().getLibrarySelection();
        onChanged();
        return this;
      }
      /**
       * <code>required string Library_Selection = 17;</code>
       */
      public Builder setLibrarySelectionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00010000;
        librarySelection_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:boa.bio.types.BioData)
    }

    static {
      defaultInstance = new BioData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:boa.bio.types.BioData)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_boa_bio_types_BioData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_boa_bio_types_BioData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\tBio.proto\022\rboa.bio.types\"\222\003\n\007BioData\022\034" +
      "\n\024Experiment_Accession\030\001 \002(\t\022\030\n\020Experime" +
      "nt_Title\030\002 \002(\t\022\025\n\rOrganism_Name\030\003 \002(\t\022\022\n" +
      "\nInstrument\030\004 \002(\t\022\021\n\tSubmitter\030\005 \001(\t\022\027\n\017" +
      "Study_Accession\030\006 \002(\t\022\023\n\013Study_Title\030\007 \002" +
      "(\t\022\030\n\020Sample_Accession\030\010 \002(\t\022\024\n\014Sample_T" +
      "itle\030\t \001(\t\022\022\n\nTotal_Size\030\n \002(\002\022\022\n\nTotal_" +
      "RUNs\030\013 \002(\003\022\023\n\013Total_Spots\030\014 \002(\003\022\023\n\013Total" +
      "_Bases\030\r \002(\003\022\024\n\014Library_Name\030\016 \002(\t\022\030\n\020Li" +
      "brary_Strategy\030\017 \002(\t\022\026\n\016Library_Source\030\020",
      " \002(\t\022\031\n\021Library_Selection\030\021 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_boa_bio_types_BioData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_boa_bio_types_BioData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_boa_bio_types_BioData_descriptor,
              new String[] { "ExperimentAccession", "ExperimentTitle", "OrganismName", "Instrument", "Submitter", "StudyAccession", "StudyTitle", "SampleAccession", "SampleTitle", "TotalSize", "TotalRUNs", "TotalSpots", "TotalBases", "LibraryName", "LibraryStrategy", "LibrarySource", "LibrarySelection", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
